/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding-complete'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'
import { Route as AppAskMeneRouteImport } from './routes/_app/ask-mene'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppBranchesRouteImport } from './routes/_app/branches'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppFollowupsRouteImport } from './routes/_app/followups'
import { Route as AppLeadersRouteImport } from './routes/_app/leaders'
import { Route as AppMembersRouteImport } from './routes/_app/members'
import { Route as AppMessagingRouteImport } from './routes/_app/messaging'
import { Route as AppMyMembersRouteImport } from './routes/_app/my-members'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppScanRouteImport } from './routes/_app/scan'
import { Route as AppServicesRouteImport } from './routes/_app/services'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStructureRouteImport } from './routes/_app/structure'
import { Route as CSubdomainRouteImport } from './routes/c.$subdomain'
import { Route as LiveSubdomainRouteImport } from './routes/live.$subdomain'
import { Route as ApiPublicAskMeneRouteImport } from './routes/api/public/ask-mene'
import { Route as ApiPublicProductHelpRouteImport } from './routes/api/public/product-help'
import { Route as ApiPublicCronMessagingRouteImport } from './routes/api/public/cron/messaging'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/onboarding-complete',
  path: '/onboarding-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAskMeneRoute = AppAskMeneRouteImport.update({
  id: '/ask-mene',
  path: '/ask-mene',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFollowupsRoute = AppFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLeadersRoute = AppLeadersRouteImport.update({
  id: '/leaders',
  path: '/leaders',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMessagingRoute = AppMessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMyMembersRoute = AppMyMembersRouteImport.update({
  id: '/my-members',
  path: '/my-members',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStructureRoute = AppStructureRouteImport.update({
  id: '/structure',
  path: '/structure',
  getParentRoute: () => AppRouteRoute,
} as any)
const CSubdomainRoute = CSubdomainRouteImport.update({
  id: '/c/$subdomain',
  path: '/c/$subdomain',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveSubdomainRoute = LiveSubdomainRouteImport.update({
  id: '/live/$subdomain',
  path: '/live/$subdomain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAskMeneRoute = ApiPublicAskMeneRouteImport.update({
  id: '/api/public/ask-mene',
  path: '/api/public/ask-mene',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductHelpRoute = ApiPublicProductHelpRouteImport.update({
  id: '/api/public/product-help',
  path: '/api/public/product-help',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronMessagingRoute = ApiPublicCronMessagingRouteImport.update({
  id: '/api/public/cron/messaging',
  path: '/api/public/cron/messaging',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-complete': typeof OnboardingCompleteRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/super-admin': typeof SuperAdminRoute
  '/terms': typeof TermsRoute
  '/accounts': typeof AppAccountsRoute
  '/ask-mene': typeof AppAskMeneRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit': typeof AppAuditRoute
  '/billing': typeof AppBillingRoute
  '/branches': typeof AppBranchesRoute
  '/dashboard': typeof AppDashboardRoute
  '/followups': typeof AppFollowupsRoute
  '/leaders': typeof AppLeadersRoute
  '/members': typeof AppMembersRoute
  '/messaging': typeof AppMessagingRoute
  '/my-members': typeof AppMyMembersRoute
  '/reports': typeof AppReportsRoute
  '/scan': typeof AppScanRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/structure': typeof AppStructureRoute
  '/c/$subdomain': typeof CSubdomainRoute
  '/live/$subdomain': typeof LiveSubdomainRoute
  '/api/public/ask-mene': typeof ApiPublicAskMeneRoute
  '/api/public/product-help': typeof ApiPublicProductHelpRoute
  '/api/public/cron/messaging': typeof ApiPublicCronMessagingRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-complete': typeof OnboardingCompleteRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/super-admin': typeof SuperAdminRoute
  '/terms': typeof TermsRoute
  '/accounts': typeof AppAccountsRoute
  '/ask-mene': typeof AppAskMeneRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit': typeof AppAuditRoute
  '/billing': typeof AppBillingRoute
  '/branches': typeof AppBranchesRoute
  '/dashboard': typeof AppDashboardRoute
  '/followups': typeof AppFollowupsRoute
  '/leaders': typeof AppLeadersRoute
  '/members': typeof AppMembersRoute
  '/messaging': typeof AppMessagingRoute
  '/my-members': typeof AppMyMembersRoute
  '/reports': typeof AppReportsRoute
  '/scan': typeof AppScanRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/structure': typeof AppStructureRoute
  '/c/$subdomain': typeof CSubdomainRoute
  '/live/$subdomain': typeof LiveSubdomainRoute
  '/api/public/ask-mene': typeof ApiPublicAskMeneRoute
  '/api/public/product-help': typeof ApiPublicProductHelpRoute
  '/api/public/cron/messaging': typeof ApiPublicCronMessagingRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-complete': typeof OnboardingCompleteRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/super-admin': typeof SuperAdminRoute
  '/terms': typeof TermsRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/ask-mene': typeof AppAskMeneRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/branches': typeof AppBranchesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/followups': typeof AppFollowupsRoute
  '/_app/leaders': typeof AppLeadersRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/messaging': typeof AppMessagingRoute
  '/_app/my-members': typeof AppMyMembersRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/structure': typeof AppStructureRoute
  '/c/$subdomain': typeof CSubdomainRoute
  '/live/$subdomain': typeof LiveSubdomainRoute
  '/api/public/ask-mene': typeof ApiPublicAskMeneRoute
  '/api/public/product-help': typeof ApiPublicProductHelpRoute
  '/api/public/cron/messaging': typeof ApiPublicCronMessagingRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/onboarding-complete'
    | '/platform'
    | '/privacy'
    | '/super-admin'
    | '/terms'
    | '/accounts'
    | '/ask-mene'
    | '/attendance'
    | '/audit'
    | '/billing'
    | '/branches'
    | '/dashboard'
    | '/followups'
    | '/leaders'
    | '/members'
    | '/messaging'
    | '/my-members'
    | '/reports'
    | '/scan'
    | '/services'
    | '/settings'
    | '/structure'
    | '/c/$subdomain'
    | '/live/$subdomain'
    | '/api/public/ask-mene'
    | '/api/public/product-help'
    | '/api/public/cron/messaging'
    | '/api/public/webhooks/paystack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/onboarding-complete'
    | '/platform'
    | '/privacy'
    | '/super-admin'
    | '/terms'
    | '/accounts'
    | '/ask-mene'
    | '/attendance'
    | '/audit'
    | '/billing'
    | '/branches'
    | '/dashboard'
    | '/followups'
    | '/leaders'
    | '/members'
    | '/messaging'
    | '/my-members'
    | '/reports'
    | '/scan'
    | '/services'
    | '/settings'
    | '/structure'
    | '/c/$subdomain'
    | '/live/$subdomain'
    | '/api/public/ask-mene'
    | '/api/public/product-help'
    | '/api/public/cron/messaging'
    | '/api/public/webhooks/paystack'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/onboarding-complete'
    | '/platform'
    | '/privacy'
    | '/super-admin'
    | '/terms'
    | '/_app/accounts'
    | '/_app/ask-mene'
    | '/_app/attendance'
    | '/_app/audit'
    | '/_app/billing'
    | '/_app/branches'
    | '/_app/dashboard'
    | '/_app/followups'
    | '/_app/leaders'
    | '/_app/members'
    | '/_app/messaging'
    | '/_app/my-members'
    | '/_app/reports'
    | '/_app/scan'
    | '/_app/services'
    | '/_app/settings'
    | '/_app/structure'
    | '/c/$subdomain'
    | '/live/$subdomain'
    | '/api/public/ask-mene'
    | '/api/public/product-help'
    | '/api/public/cron/messaging'
    | '/api/public/webhooks/paystack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  PlatformRoute: typeof PlatformRoute
  PrivacyRoute: typeof PrivacyRoute
  SuperAdminRoute: typeof SuperAdminRoute
  TermsRoute: typeof TermsRoute
  CSubdomainRoute: typeof CSubdomainRoute
  LiveSubdomainRoute: typeof LiveSubdomainRoute
  ApiPublicAskMeneRoute: typeof ApiPublicAskMeneRoute
  ApiPublicProductHelpRoute: typeof ApiPublicProductHelpRoute
  ApiPublicCronMessagingRoute: typeof ApiPublicCronMessagingRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-complete': {
      id: '/onboarding-complete'
      path: '/onboarding-complete'
      fullPath: '/onboarding-complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ask-mene': {
      id: '/_app/ask-mene'
      path: '/ask-mene'
      fullPath: '/ask-mene'
      preLoaderRoute: typeof AppAskMeneRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/branches': {
      id: '/_app/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/followups': {
      id: '/_app/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof AppFollowupsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/leaders': {
      id: '/_app/leaders'
      path: '/leaders'
      fullPath: '/leaders'
      preLoaderRoute: typeof AppLeadersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/messaging': {
      id: '/_app/messaging'
      path: '/messaging'
      fullPath: '/messaging'
      preLoaderRoute: typeof AppMessagingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/my-members': {
      id: '/_app/my-members'
      path: '/my-members'
      fullPath: '/my-members'
      preLoaderRoute: typeof AppMyMembersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/structure': {
      id: '/_app/structure'
      path: '/structure'
      fullPath: '/structure'
      preLoaderRoute: typeof AppStructureRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/c/$subdomain': {
      id: '/c/$subdomain'
      path: '/c/$subdomain'
      fullPath: '/c/$subdomain'
      preLoaderRoute: typeof CSubdomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$subdomain': {
      id: '/live/$subdomain'
      path: '/live/$subdomain'
      fullPath: '/live/$subdomain'
      preLoaderRoute: typeof LiveSubdomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ask-mene': {
      id: '/api/public/ask-mene'
      path: '/api/public/ask-mene'
      fullPath: '/api/public/ask-mene'
      preLoaderRoute: typeof ApiPublicAskMeneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/product-help': {
      id: '/api/public/product-help'
      path: '/api/public/product-help'
      fullPath: '/api/public/product-help'
      preLoaderRoute: typeof ApiPublicProductHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/messaging': {
      id: '/api/public/cron/messaging'
      path: '/api/public/cron/messaging'
      fullPath: '/api/public/cron/messaging'
      preLoaderRoute: typeof ApiPublicCronMessagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppAskMeneRoute: typeof AppAskMeneRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBranchesRoute: typeof AppBranchesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFollowupsRoute: typeof AppFollowupsRoute
  AppLeadersRoute: typeof AppLeadersRoute
  AppMembersRoute: typeof AppMembersRoute
  AppMessagingRoute: typeof AppMessagingRoute
  AppMyMembersRoute: typeof AppMyMembersRoute
  AppReportsRoute: typeof AppReportsRoute
  AppScanRoute: typeof AppScanRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStructureRoute: typeof AppStructureRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppAskMeneRoute: AppAskMeneRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppAuditRoute: AppAuditRoute,
  AppBillingRoute: AppBillingRoute,
  AppBranchesRoute: AppBranchesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFollowupsRoute: AppFollowupsRoute,
  AppLeadersRoute: AppLeadersRoute,
  AppMembersRoute: AppMembersRoute,
  AppMessagingRoute: AppMessagingRoute,
  AppMyMembersRoute: AppMyMembersRoute,
  AppReportsRoute: AppReportsRoute,
  AppScanRoute: AppScanRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStructureRoute: AppStructureRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  PlatformRoute: PlatformRoute,
  PrivacyRoute: PrivacyRoute,
  SuperAdminRoute: SuperAdminRoute,
  TermsRoute: TermsRoute,
  CSubdomainRoute: CSubdomainRoute,
  LiveSubdomainRoute: LiveSubdomainRoute,
  ApiPublicAskMeneRoute: ApiPublicAskMeneRoute,
  ApiPublicProductHelpRoute: ApiPublicProductHelpRoute,
  ApiPublicCronMessagingRoute: ApiPublicCronMessagingRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
